# eslint-disable no-irregular-whitespace, yaml/no-irregular-whitespace
# prettier-ignore
name: â€ƒ

on:
  workflow_call:
    inputs:
      ref:
        description: "Force checkout a specific git ref (branch, tag, commit)"
        type: string

concurrency:
  group: deploy
  cancel-in-progress: false # canceling could break state

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: pnpm install
        uses: falcondev-it/.github/actions/pnpm-install@master
        with:
          ref: ${{ inputs.ref }}
          registry-url: https://registry.npmjs.org

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm -r publish --access=public --provenance --no-git-checks --tag $(npx simple-dist-tag)
